In [1]:
import numpy as np
feats=np.loadtxt('data_307_1006ec_feat.txt')
feats

array([[33.,  1.,  1., ...,  1.,  1.,  1.],
       [52.,  1.,  1., ...,  1.,  1.,  1.],
       [ 5.,  1.,  3., ...,  1.,  1.,  1.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [2]:
feat=feats/5000
feat

array([[0.0066, 0.0002, 0.0002, ..., 0.0002, 0.0002, 0.0002],
       [0.0104, 0.0002, 0.0002, ..., 0.0002, 0.0002, 0.0002],
       [0.001 , 0.0002, 0.0006, ..., 0.0002, 0.0002, 0.0002],
       ...,
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ]])

In [3]:
np.savetxt('data_1006_307_feat.txt',feat,delimiter=',')

In [4]:
feats=np.loadtxt('data_1006_307_feat.txt',delimiter=',')
feats

array([[0.0066, 0.0002, 0.0002, ..., 0.0002, 0.0002, 0.0002],
       [0.0104, 0.0002, 0.0002, ..., 0.0002, 0.0002, 0.0002],
       [0.001 , 0.0002, 0.0006, ..., 0.0002, 0.0002, 0.0002],
       ...,
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ]])

In [6]:
cor=np.loadtxt('data_307_1006_3cor.txt')
cor

array([[ 92., 102.,  26.],
       [ 93., 102.,  26.],
       [ 92., 103.,  26.],
       ...,
       [ 94., 103.,  42.],
       [ 94., 104.,  42.],
       [ 94., 102.,  43.]])

In [7]:
np.savetxt('data_1006_307_3cor.txt',cor,fmt='%d',delimiter=',')

In [3]:
import torch.nn.functional as F
import numpy as np

In [4]:
labels=np.loadtxt('data_1006_307_labels.txt')

In [5]:
labels

array([0., 0., 0., ..., 1., 0., 0.])

In [7]:
f1=np.one_hot(labels,2)

AttributeError: module 'numpy' has no attribute 'one_hot'