In [5]:
import numpy as np
feats=np.loadtxt('data_1025_307_feat.txt',delimiter=',')

In [7]:
feats[1]

array([2.000e-04, 4.000e-04, 2.000e-04, 2.000e-04, 5.360e-02, 0.000e+00,
       2.680e-01, 1.200e-03, 6.200e-03, 4.500e-02, 9.600e-03, 2.000e-04,
       9.750e-01, 0.000e+00, 2.000e-04, 1.000e-03, 2.000e-04, 2.000e-04,
       0.000e+00, 2.000e-04, 1.102e-01, 8.000e-04, 4.000e-04, 4.000e-04,
       1.000e+00, 2.000e-04, 4.000e-04, 2.000e-04, 1.000e-03, 1.200e-03,
       8.000e-04, 0.000e+00, 0.000e+00, 2.000e-04, 2.000e-04, 2.000e-04,
       2.000e-04, 2.000e-04, 2.000e-04, 2.000e-04, 0.000e+00, 2.000e-04,
       2.000e-04, 2.000e-04, 2.000e-04, 4.000e-04, 0.000e+00, 2.000e-04,
       0.000e+00, 2.000e-04, 2.000e-04, 2.000e-04, 2.000e-04, 0.000e+00,
       0.000e+00, 4.000e-03, 2.000e-04, 2.000e-04, 2.000e-04, 2.000e-04,
       0.000e+00, 2.000e-04, 2.000e-04, 2.000e-04, 2.000e-04, 2.000e-04,
       0.000e+00, 0.000e+00, 2.000e-04, 2.000e-04])

In [3]:
np.savetxt('data_1025_307_feat.txt',feat,fmt='%d',delimiter=',')

In [8]:
feats[1]/5000

array([1.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 2.680e+02, 0.000e+00,
       1.340e+03, 6.000e+00, 3.100e+01, 2.250e+02, 4.800e+01, 1.000e+00,
       4.875e+03, 0.000e+00, 1.000e+00, 5.000e+00, 1.000e+00, 1.000e+00,
       0.000e+00, 1.000e+00, 5.510e+02, 4.000e+00, 2.000e+00, 2.000e+00,
       5.000e+03, 1.000e+00, 2.000e+00, 1.000e+00, 5.000e+00, 6.000e+00,
       4.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 2.000e+00, 0.000e+00, 1.000e+00,
       0.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 0.000e+00,
       0.000e+00, 2.000e+01, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       0.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00])

In [2]:
feat=feats/5000

In [3]:
feat[1]

array([2.000e-04, 4.000e-04, 2.000e-04, 2.000e-04, 5.360e-02, 0.000e+00,
       2.680e-01, 1.200e-03, 6.200e-03, 4.500e-02, 9.600e-03, 2.000e-04,
       9.750e-01, 0.000e+00, 2.000e-04, 1.000e-03, 2.000e-04, 2.000e-04,
       0.000e+00, 2.000e-04, 1.102e-01, 8.000e-04, 4.000e-04, 4.000e-04,
       1.000e+00, 2.000e-04, 4.000e-04, 2.000e-04, 1.000e-03, 1.200e-03,
       8.000e-04, 0.000e+00, 0.000e+00, 2.000e-04, 2.000e-04, 2.000e-04,
       2.000e-04, 2.000e-04, 2.000e-04, 2.000e-04, 0.000e+00, 2.000e-04,
       2.000e-04, 2.000e-04, 2.000e-04, 4.000e-04, 0.000e+00, 2.000e-04,
       0.000e+00, 2.000e-04, 2.000e-04, 2.000e-04, 2.000e-04, 0.000e+00,
       0.000e+00, 4.000e-03, 2.000e-04, 2.000e-04, 2.000e-04, 2.000e-04,
       0.000e+00, 2.000e-04, 2.000e-04, 2.000e-04, 2.000e-04, 2.000e-04,
       0.000e+00, 0.000e+00, 2.000e-04, 2.000e-04])

In [4]:
np.savetxt('data_1025_307_feat.txt',feat,delimiter=',')